# Generated by Django 5.0.4 on 2025-01-01 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_cf', models.FloatField()),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nilai_cf_terdeteksi', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to=settings.AUTH_USER_MODEL)),
                ('penyakit_terdeteksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='HasilPenyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_cf', models.FloatField()),
                ('hasil_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_penyakit', to='diagnosis.hasilkuis')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nilai_cf', models.FloatField(default=0)),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.FloatField()),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bobot', to='diagnosis.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bobot', to='diagnosis.penyakit')),
            ],
        ),
    ]
