# Generated by Django 5.0.4 on 2025-01-01 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuis',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='hasilkuis',
            unique_together={('user', 'tanggal')},
        ),
        migrations.AlterUniqueTogether(
            name='hasilpenyakit',
            unique_together={('hasil_kuis', 'penyakit')},
        ),
    ]
